### ISSUE TITLE
google photos to big for screen

### ISSUE THREAD

**Issue by ca1p3** [j-a-n/lovelace-wallpanel#118]
hello im using google photos as screensaver but all the photos are zoomed in so they dont look good and dosent fit the screen. is there a way to solve this ?

**Comment by amondit** [comment]
Hello, have you played with the 'crop mode' setting of the google photo integration? I've experienced the same thing until I found out that one setting was resizing the pictures to a small resolution (don't remember which setting though)

**Comment by Daanoz** [comment]
Maintainer of the Google Photo's integration here, I think I replicated/found the issue. If the crop mode of your Google Photos album is on `Original`, that means no cropping is applied. This means that (downwards) scaling is used to fit the image in the given boundaries.

For example; your image is portrait 1000x3000; but your screen/window is landscape at 1500x1000. It will scale the image down to fully fit in your screen without cutting bits of the image. The image loaded will end up being roughly 333x1000 (both sides divided by 3). 

This in itself is not the reason why they are blurry and zoomed in. Looking at the [configuration](https://github.com/j-a-n/lovelace-wallpanel#configuration) of the lovelave-wallpanel, the default value for `image_fit` is `cover`. This cover setting means, that the image renderer will take that 333x1000 image, and scale it upwards to be 1500x4500, center it in the middle of the container and cut of the sides. Naturally this leads to the blurry/zoomed image you are seeing.

I got two solutions:
- Set `image_fit` for the lovelace-wallpanel to `container` (this will create black bars around the image, but retain the entire image)
- Set the crop mode of the Google Photo's integration to either `Crop` or `Combine images` (this will download an image large enough to match the container size, avoiding the upscaling that `cover` does. Warning: if the source image is too small, it might still lead to blurry images)

I have updated the [docs](https://github.com/Daanoz/ha-google-photos#lovelace-wall-panel) on the Google Photo's integration side to document this.

**Comment by amondit** [comment]
Thank you @Daanoz for the feedback, that is indeed what I experienced.

I was playing with the `original` crop setting in order to get the full dimensions of the picture, and try to implement a kind-of dynamic pan & zoom effect on the picture, but since the resolution was much too small, it was quite ugly (and already quite ugly without doing anything due to the `cover` css resizing). (never achieved much though, as I'm more of a backend guy anyway)

`crop` setting did not work for what I was trying to achieve, due to the fact that the image was already cut to the viewport dimensions (and zooming out made things ugly). I guess it might be because I was trying to do things directly in the browser dev tools, and that the g-photos integrations did not know in advance of the final, zoomed-out dimensions and thus wasn't able to requested the pictures set to the increased size. Maybe if the photo container is set to the right size before the g-photo integration refreshes the picture, it might be able to be set to the right size?

Thanks.

**Comment by ca1p3** [comment]
@Daanoz thanks for the solution i set the image_fit to contain then i used combine images in Google Photos and it works great now 👍

**Comment by ceinmart** [comment]
Hi , sorry to revive this post now. 
However, I've configured my google photos with crop and image_fit = contain and still get photos cropped on the screen.
Apparently, the photos were taken in portrait mode... 

Any tips?
My desire is make the photo fit to the screen, no matter if will have a black , blurry on sides...

**Comment by ceinmart** [comment]
Just solved!
Google Photos = original
image_fit = scale-down 

Worked!
