### ISSUE TITLE
Stop screensaver at interaction with cards

### ISSUE THREAD

**Issue by kwithus** [j-a-n/lovelace-wallpanel#120]
I love the new option to interact with cards on the wallpanel.
However, there is currently a limitation, which I don’t know how to solve.
Generally it’s absolut ok and as intended, that the screensaver does not stop when interact with a card (e.g. tapping to show additional information), but..-
When I use the option to navigate on tap to a different tab, the screensaver also does not stop, when it is also enabled on this other tab. By that, the tap does navigate to the other tab, however I can’t see it, as the screensaver is active.
So currently the ‚solution‘ is to exclude this other tab from the „enabled on“ list. Downside, once navigated to the other tab, the screensaver doesn’t start again, unless I navigate manually back to the default tab. 
would be great, if the screensaver does stop, when an interaction results in navigation to another tab and then comes back again after the idle time.

**Comment by OCT0PUSCRIME** [comment]
+1 on this. I use Browser Mod popup cards with the fire-dom-event instead of going to another tab, so the workaround mentioned by kwithus does not work for me. When a card pops up I can interact with it for only a few seconds before the screensaver starts, and I can't dismiss the screensaver at that point unless I click on the edge of the tablet, outside of where the pop up would be.

**Comment by j-a-n** [comment]
This is now implemented in version 4.12.0.
The screensaver will be stopped on all `location-changed` dom events if `stop_screensaver_on_location_change` is set to `true`, which is the default.

**Comment by kwithus** [comment]
Perfect! Thanks!
