### ISSUE TITLE
Immich connection not possible - No info in logs

### ISSUE THREAD

**Issue by PottiMc** [j-a-n/lovelace-wallpanel#290]
Hi,
I am trying to get my (local) Immich pictures as a wallpanel background as described in your documentation. Since I can locally connect from HA to immich I don't have any reverse proxy rules to adjust.
I can connect with other applications to my api, e.g. Immich Power Tools or the Immich integration in HA. So the connection is working I guess.

Here is my config related to immich:
  image_url: immich+http://192.XXX.XXX.XX:2283/api
  immich_api_key: XXXDDSABiRHXVXVYukfXXX8QEFuM6qXXXw
  immich_resolution: original

The screen does not show an image at all. In the debug logs I can just see the url and the config values, no error message or something.

Running WallPanel 4.30.0 and HA 2024.10.1.

**Comment by j-a-n** [comment]
Please have a look at the browser console (F12).
Most probably a CORS issue.
Since there is no possibility to set CORS headers in immich directly you probably need to setup an reverse proxy like traefik or nginx.

**Comment by nick3189** [comment]
I have the same problem and I'm still investigating but thought I'd share some more details in case it helps.
I had an nginx server running already so I setup CORS headers on a proxy entry on it to try to resolve this. If I browse to it directly in a new browser tab (e.g. <ip>/api/albums) then I can see the headers in the response in the browser so I know that worked. However when I point wallpanel at it, view from Home Assistant and look at the network tab, there are no response headers and it looks like the browser didn't even make a request. This is the same result in Firefox, Chrome and Brave. I'm wondering if it because the request header 'Referrer Policy:' is set to 'same-origin'.
